name: Build
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout	
        uses: actions/checkout@v4.2.2
        with:
          submodules: recursive
      - name: Build
        run: |
          ./gradlew run
      - name: Set Node.js 18.x
        uses: actions/setup-node@v4.2.0
        with:
          node-version: 18.x
      - name: Run yarn install
        uses: borales/actions-yarn@v4
        with:
         dir: 'website'
         cmd: install # will run `yarn install` command
      - name: Run yarn build
        uses: borales/actions-yarn@v4
        with:
          dir: 'website'
          cmd: run build # will run `yarn test` command     
      - name: Merge
        run: |
          cp -a output/. website/public/
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: website/public
