on:
  pull_request_target:
    types: [opened]
jobs:
  comment_on_pr:
    runs-on: ubuntu-latest
    name: Comment after PR is submitted
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
            Thank you for submitting a pull request! Please note that due to the high volume of contributions, we can only review PRs that pass all CI checks. If your PR has failing checks, we recommend reviewing the documentation and examining merged PRs for guidance on resolving issues. Once all CI checks pass, your PR will be eligible for review. If you make changes after a requested review, please remember to re-request a review to ensure it is revisited. Thank you for your understanding and support!