name: Run prettier check

on:
  push:
  pull_request:
  merge_group:

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4.2.2

      - uses: actions/cache@v4
        name: Configure npm caching
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ runner.arch }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install Prettier explicitly
        run: npm install -g prettier@3.8.3

      - name: Run prettier
        run: prettier --check "_data/*/*.json"
