name: Check JSON Schema

on:
  push:
  pull_request:

jobs:
  validate_json:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v4
    - uses: actions/cache@v4
      name: Configure npm caching
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/workflows/validate_json.yml') }}
        restore-keys: |
          ${{ runner.os }}-npm-
    - name: Run JSON Validation
      working-directory: ./tools
      run: |-
        npm install
        node schemaCheck.js
